//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Star_Wars_Character_Finder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Star_Wars_Character_Finder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baby_yoda {
            get {
                object obj = ResourceManager.GetObject("baby_yoda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Starjedi {
            get {
                object obj = ResourceManager.GetObject("Starjedi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap starwars_logo {
            get {
                object obj = ResourceManager.GetObject("starwars_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap starwarscharacterbackground1 {
            get {
                object obj = ResourceManager.GetObject("starwarscharacterbackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANAKIN
        ///DARTH VADER
        ///LUKE
        ///OBI-WAN
        ///C-3PO
        ///R2-D2
        ///CHEWBACCA
        ///HAN
        ///LEIA
        ///PADME
        ///QUI-GON
        ///EMPEROR
        ///YODA
        ///JAR JAR
        ///LANDO
        ///RED LEADER
        ///WEDGE
        ///BAIL ORGANA
        ///CAPTAIN PANAKA
        ///MACE WINDU
        ///NUTE GUNRAY
        ///BIGGS
        ///GOLD LEADER
        ///GENERAL GRIEVOUS
        ///TARKIN
        ///PIETT
        ///FODE/BEED
        ///RIC OLIE
        ///SHMI
        ///RUNE
        ///BOBA FETT
        ///OWEN
        ///ADMIRAL ACKBAR
        ///WATTO
        ///LAMA SU
        ///COUNT DOOKU
        ///GOLD FIVE
        ///RED TEN
        ///SIO BIBBLE
        ///JABBA
        ///MAD MADDA
        ///TAUN WE
        ///RIEEKAN
        ///CAPTAIN TYPHO
        ///ZEV
        ///DARTH MAUL
        ///BRAVO TWO
        ///JANGO FETT
        ///BOSS NASS
        ///GENERAL CEEL
        ///TEY HOW
        ///TC-14
        ///KITSTER
        ///RUWEE
        ///CLONE COMMANDER CODY
        ///CLONE COMMANDER GREE
        ///KI-A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StarWarsCharacters {
            get {
                return ResourceManager.GetString("StarWarsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon starwarslogoicon {
            get {
                object obj = ResourceManager.GetObject("starwarslogoicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
